language: ruby
rvm: 2.5.1
services: postgresql
cache: bundler
before_script:
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:create
- bundle exec rake db:migrate
script: bundle exec rspec spec/
env:
  global:
    secure: oG65O4PDAnZ1sAPQOR11l0QUMu4Zt0UKGaOnRx2jhOpq76SxV1aQavYbcJHzjHIEiYca2vvxcZD1qGSVjr3FSdmhD0+q+TWk5NsbomIRv3/6Te37sKZ+MV5ox9tGAMJdQ52t7lsPG80WjsUPavr+8THDAfmYCmGYtZIhfz41wGN1ckD9Wju7o0V5K76QjkcMKTjt2PC8rBJ5KWexSLnCVvDQuHUobROcPb0onDGUK5aUE96hoAeRNNSBsHjWHeefTxQHw7MQreqiMkCjoKPnE0Xh8aealIDu9Rj5CsSgLqJmGtfqq3OuEDc+A7zp+rsiPB2QN2u4TQz7hIwbKwRPEcEzGXtY4LjSU/+iteIbUH9mnKB9L+uXahNIk1//tvqiVOZJ8Ua56KdOkEq91/hxd3cG33CLHzs+1NclhPRG2rKVdpbCjLO4J2CJ6/09tQCdrtOLGbfuLH/hIPk85MiEzm0Z9pe21dSdTkKbKxSWm4MVP3kyz05GgHJPx6TBNyQs4hE7QqRwFq4zSGoYssaUoB93eUGpkTYCIEX45uRi8peCG4jnToCcxLIMIkfjwRYOyYYJiUcTRgM40kp0kZ6JAlqcICDrYTlC/GVIy27uT9G/+cCamqXrN9UDyzJ1fJf0l+AVoIrrkBUJ8Y+MAJVmZWtvFwrJIdPjo39L2lMJ0w0=
notifications:
  slack:
    secure: VV7k118N7iMLzkz1iw0m+esGgtZF1oPEkAZ0GDTvtr0oa3EgjxDoUSTkKyH83mVQPt31V6UvK7f/HorXUJ4Y91A2mg863vO7z9TmOet79eQZZ9AMQ9MyAKbn1wqhwyDerpiUOfUxXlW9uYgYaVieWbJKLV/sqAeT0dgnpdUwYzRRpJfGJ5lay5l5z/C9wHnybRgcnPshIMoIr9BEENYWwy6sc1i+B9zhupyvPxmAV+lEK7b/Vn5V4zQXGo93D/V3m4yVcEFLjHHC4pSLXU+aJBO9ATV53VTQJi0zPzUx+okf0wwDPb7+mRUJI/gxWn4xlze8eptghB8tbpP73nHMwcoixJiziZEOzFNElosfpSU+QtYql7e95f990qfti/xhD1IE+Hlqx1BX4XJVZ5izjwVykdfmhvHqou+iCvWQbMYp5GL0UpjDz70/4VVrTQmreqKEofEzMgjPEyPQsjoqlhYiZfOzS03pt4DGb3CIElGp9Rweja4Y5nIhV09m05eaFBZnU7IGiCtI1HCns/9isjri3fGxMJlBuJq86BQGx4dMZWKo+PBo505vaSXM8RBzrfaAIf9UL2PDd+SacYOyfg493/MBsnVJI9Nzx0RwMJFYLEt4oQrvE4kiQBTIoF6czN3tiUWxkkTv03gtpTwmha/DmWtXfqVy4NQRtxoWhUc=
